apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB:-velov}
    user: ${POSTGRES_USER:-velov}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-velov}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: true
